const { GoogleGenAI } = require("@google/genai")
const { z } = require("zod")
const { zodToJsonSchema } = require("zod-to-json-schema")
const puppeteer = require("puppeteer")

const ai = new GoogleGenAI({
  apiKey: process.env.GOOGLE_GEN_API_KEY
})


const interviewReportSchema = z.object({
  matchScore: z.number(),

  technicalQuestions: z.array(
    z.object({
      question: z.string(),
      intention: z.string(),
      answer: z.string()
    })
  ).min(5),

  behavioralQuestions: z.array(
    z.object({
      question: z.string(),
      intention: z.string(),
      answer: z.string()
    })
  ).min(3),

  skillGaps: z.array(
    z.object({
      skill: z.string(),
severity: z.enum(["low", "medium", "high"]).default("medium")    })
  ).min(2),

  preparationPlan: z.array(
    z.object({
      day: z.number(),
      focus: z.string(),
      tasks: z.array(z.string()).min(2)
    })
  ).min(5),

  title: z.string()
})

async function generateInterviewReport({ resume, selfDescription, jobDescription }) {


const prompt = `
You are an expert technical interviewer and career coach.

Generate a COMPLETE interview preparation report in STRICT JSON format.

IMPORTANT:
- Return ONLY raw JSON
- No markdown
- No explanation
- No extra text
- No code block

The JSON must EXACTLY follow this structure:

{
  "matchScore": number,
  "title": string,
  "technicalQuestions": [
    {
      "question": string,
      "intention": string,
      "answer": string
    }
  ],
  "behavioralQuestions": [
    {
      "question": string,
      "intention": string,
      "answer": string
    }
  ],
"skillGaps": [
  {
    "skill": string,
    "severity": "low" | "medium" | "high"
  }
]

IMPORTANT:
EVERY object inside skillGaps MUST contain BOTH:
- skill
- severity

severity can ONLY be:
- low
- medium
- high
  "preparationPlan": [
    {
      "day": number,
      "focus": string,
      "tasks": [string]
    }
  ]
}

STRICT REQUIREMENTS:
- Minimum 5 technical questions
- Minimum 3 behavioral questions
- Minimum 2 skill gaps
- Minimum 5 preparation plan days
- Do NOT leave arrays empty

Resume:
${resume}

Self Description:
${selfDescription}

Job Description:
${jobDescription}
Do NOT omit any fields from objects.
Every object must contain all required properties.
`
  const response = await ai.models.generateContent({
    // model: "gemini-3-flash-preview",
    model: "gemini-2.5-flash", contents: prompt,
    config: {
      responseMimeType: "application/json",
      // responseSchema: zodToJsonSchema(interviewReportSchema),
    }
  })
const rawText = response.text
  console.log("RAW RESPONSE:")
  console.log(rawText)

  const cleaned = rawText
    .replace(/```json/g, "")
    .replace(/```/g, "")
    .trim()

  const jsonData = JSON.parse(cleaned)

  const validatedData =
    interviewReportSchema.parse(jsonData)

  return validatedData

}



async function generatePdfFromHtml(htmlContent) {
  const browser = await puppeteer.launch()
  const page = await browser.newPage();
  await page.setContent(htmlContent, { waitUntil: "networkidle0" })

  const pdfBuffer = await page.pdf({
    format: "A4", margin: {
      top: "20mm",
      bottom: "20mm",
      left: "15mm",
      right: "15mm"
    }
  })

  await browser.close()

  return pdfBuffer
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {

  const resumePdfSchema = z.object({
    html: z.string().describe("The HTML content of the resume which can be converted to PDF using any library like puppeteer")
  })

  const prompt = `Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
                    `

  const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      responseSchema: zodToJsonSchema(resumePdfSchema),
    }
  })


  const jsonContent = JSON.parse(response.text)

  const pdfBuffer = await generatePdfFromHtml(jsonContent.html)

  return pdfBuffer

}

module.exports = { generateInterviewReport, generateResumePdf }